const state = { token: localStorage.getItem('riskledger_token'), refreshToken: localStorage.getItem('riskledger_refresh_token'), email: localStorage.getItem('riskledger_email'), portfolios: [], portfolioId: localStorage.getItem('riskledger_portfolio') };
const $ = (selector) => document.querySelector(selector);
const api = async (path, options = {}) => {
  const headers = { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}) };
  if (state.token) headers.Authorization = `Bearer ${state.token}`;
  let response = await fetch(path, { ...options, credentials: 'same-origin', headers });
  if (response.status === 401 && !options.skipRefresh && path !== '/api/v1/auth/refresh') {
    const refreshHeaders = state.refreshToken ? { Authorization: `Bearer ${state.refreshToken}` } : {};
    const refreshed = await fetch('/api/v1/auth/refresh', { method: 'POST', credentials: 'same-origin', headers: refreshHeaders });
    if (refreshed.ok) {
      const session = await refreshed.json();
      state.token = session.token;
      localStorage.setItem('riskledger_token', state.token);
      headers.Authorization = `Bearer ${state.token}`;
      response = await fetch(path, { ...options, credentials: 'same-origin', headers });
    }
  }
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
  return data;
};
const money = (value) => new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(Number(value || 0));
const toast = (message, error = false) => { const node = $('#toast'); node.textContent = message; node.style.background = error ? '#ad4d23' : '#162329'; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2800); };
const selectedPortfolio = () => state.portfolios.find((item) => item.id === state.portfolioId) || state.portfolios[0];
const setView = (loggedIn) => { $('#auth-view').classList.toggle('hidden', loggedIn); $('#app-view').classList.toggle('hidden', !loggedIn); if (loggedIn) $('#user-email').textContent = state.email || ''; };
const showPage = (section) => { document.querySelectorAll('.page-section').forEach((node) => node.classList.add('hidden')); $(`#${section}-section`).classList.remove('hidden'); document.querySelectorAll('.nav-item').forEach((node) => node.classList.toggle('active', node.dataset.section === section)); $('#page-title').textContent = section === 'overview' ? 'Обзор' : section === 'trades' ? 'Сделки' : section === 'analytics' ? 'Аналитика' : section === 'ledger' ? 'Ledger' : 'Лимиты риска'; if (section === 'trades') { loadTrades(); loadBrokerImports(); } if (section === 'analytics') loadAnalytics(); if (section === 'ledger') loadLedger(); if (section === 'risk') { loadLimits(); loadRiskSnapshot(); updateScenarioControls(); loadAlerts(); } };
async function loadPortfolios() { state.portfolios = await api('/api/v1/portfolios'); if (!state.portfolioId || !state.portfolios.some((item) => item.id === state.portfolioId)) state.portfolioId = state.portfolios[0]?.id; localStorage.setItem('riskledger_portfolio', state.portfolioId || ''); const select = $('#portfolio-select'); select.innerHTML = state.portfolios.map((item) => `<option value="${item.id}">${item.name} · ${item.base_currency}</option>`).join(''); select.value = state.portfolioId || ''; await loadDashboard(); }
async function loadDashboard() { const portfolio = selectedPortfolio(); if (!portfolio) { $('#positions').innerHTML = '<div class="empty">Сначала создайте портфель.</div>'; return; } const query = `?portfolio_id=${encodeURIComponent(portfolio.id)}`; const [summary, positions] = await Promise.all([api(`/api/v1/summary${query}`), api(`/api/v1/positions${query}`)]); $('#total-value').textContent = money(summary.total_value); $('#realized-pnl').textContent = money(summary.realized_pnl); $('#unrealized-pnl').textContent = money(summary.unrealized_pnl); $('#risk-count').textContent = summary.active_risk_events; $('#positions').innerHTML = positions.length ? positions.map((position) => `<div class="position-row"><strong>${position.instrument}<span class="subtext">${position.quantity} ед.</span></strong><span>${money(position.average_entry_price)}<span class="subtext">Средняя цена</span></span><span>${money(position.market_value)}<span class="subtext">Стоимость</span></span><strong class="${position.unrealized_pnl >= 0 ? 'positive' : ''}">${money(position.unrealized_pnl)}</strong></div>`).join('') : '<div class="empty">Открытых позиций пока нет.</div>'; }
async function loadTrades() { const portfolio = selectedPortfolio(); if (!portfolio) return; const list = $('#trades-list'); list.innerHTML = '<div class="empty">Загрузка сделок...</div>'; try { const trades = await api(`/api/v1/trades?portfolio_id=${encodeURIComponent(portfolio.id)}`); list.innerHTML = trades.length ? trades.map((trade) => `<div class="trade-row"><span class="badge ${trade.side}">${trade.side === 'buy' ? 'ПОКУПКА' : 'ПРОДАЖА'}</span><strong>${trade.instrument}<span class="subtext">${new Date(trade.executed_at).toLocaleString('ru-RU')}</span></strong><span>${trade.quantity} ед.</span><strong>${money(trade.price)}</strong></div>`).join('') : '<div class="empty">Сделок пока нет.</div>'; } catch (error) { list.innerHTML = `<div class="empty">${error.message}</div>`; } }
async function loadBrokerImports() { const portfolio = selectedPortfolio(); if (!portfolio) return; try { const batches = await api(`/api/v1/imports?portfolio_id=${encodeURIComponent(portfolio.id)}`); $('#import-batches').innerHTML = batches.length ? batches.map((batch) => `<div class="import-batch"><strong>${batch.source}</strong><span>${batch.filename}</span><span>${batch.matched}/${batch.total} matched</span><span class="${batch.needs_review ? 'review-count' : 'positive'}">${batch.needs_review} review</span></div>`).join('') : '<div class="empty">Импорты ещё не запускались.</div>'; } catch (error) { $('#import-batches').innerHTML = `<div class="empty">${error.message}</div>`; } }
async function loadLimits() { const portfolio = selectedPortfolio(); if (!portfolio) return; const limits = await api(`/api/v1/risk-limits?portfolio_id=${encodeURIComponent(portfolio.id)}`); $('#limits-list').innerHTML = limits.length ? limits.map((limit) => `<div class="limit-row"><strong>${limit.type === 'max_portfolio_value' ? 'Максимальная стоимость' : limit.type}</strong><span>${money(limit.value)}</span><span>${limit.enabled ? 'Включён' : 'Выключен'}</span></div>`).join('') : '<div class="empty">Лимиты пока не настроены.</div>'; }
async function loadAlerts() { const portfolio = selectedPortfolio(); if (!portfolio) return; if (!$('#alert-surface')) { $('#risk-section').insertAdjacentHTML('beforeend', '<div id="alert-surface" class="split-grid alert-compliance-grid"><article class="panel"><div class="panel-heading"><div><p class="eyebrow">Risk alerts</p><h3>Правила оповещения</h3></div><button id="evaluate-alerts" class="secondary">Проверить сейчас</button></div><form id="alert-rule-form" class="stack-form"><div class="form-row"><label>Тип<select id="alert-type"><option value="breach">Breach</option><option value="drawdown">Drawdown</option><option value="concentration">Concentration</option><option value="limits">Limits</option><option value="unusual_activity">Unusual activity</option></select></label><label>Порог<input id="alert-threshold" type="number" min="0" step="any" value="70"></label></div><div class="form-row"><label>Severity<select id="alert-severity"><option value="warning">Warning</option><option value="critical">Critical</option><option value="info">Info</option></select></label><label>Каналы<select id="alert-channels" multiple><option value="email" selected>Email</option><option value="telegram">Telegram</option><option value="slack">Slack</option><option value="webhook">Webhook</option></select></label></div><button class="primary wide" type="submit">Сохранить правило</button></form><div id="alert-rules" class="limits-list"></div></article><article class="panel"><p class="eyebrow">История соблюдения</p><h3>Alert & audit trail</h3><div id="alert-events" class="compliance-list"></div><div id="audit-log" class="compliance-list"></div></article></div>'); $('#alert-rule-form').addEventListener('submit', async (event) => { event.preventDefault(); const channels = Array.from($('#alert-channels').selectedOptions).map((option) => option.value); try { await api('/api/v1/risk-alert-rules', { method: 'POST', body: JSON.stringify({ portfolio_id: selectedPortfolio().id, type: $('#alert-type').value, threshold: Number($('#alert-threshold').value), severity: $('#alert-severity').value, channels }) }); toast('Правило сохранено'); await loadAlerts(); } catch (error) { toast(error.message, true); } }); $('#evaluate-alerts').addEventListener('click', async () => { try { await api(`/api/v1/risk-alerts/evaluate?portfolio_id=${encodeURIComponent(selectedPortfolio().id)}`, { method: 'POST' }); toast('Алерты проверены'); await loadAlerts(); } catch (error) { toast(error.message, true); } }); }
try { const query = `?portfolio_id=${encodeURIComponent(portfolio.id)}`; const [rules, events, audit] = await Promise.all([api(`/api/v1/risk-alert-rules${query}`), api(`/api/v1/risk-alert-events${query}`), api(`/api/v1/audit-log${query}`)]); $('#alert-rules').innerHTML = rules.length ? rules.map((rule) => `<div class="limit-row"><strong>${rule.type}</strong><span>${rule.threshold}</span><span>${rule.channels.join(', ')}</span></div>`).join('') : '<div class="empty">Правила ещё не настроены.</div>'; $('#alert-events').innerHTML = events.length ? events.slice(0, 8).map((event) => `<div class="compliance-row"><strong>${event.type}</strong><span>${event.message}</span><small>${event.status} · ${new Date(event.triggered_at).toLocaleString('ru-RU')}</small></div>`).join('') : '<div class="empty">Срабатываний пока нет.</div>'; $('#audit-log').innerHTML = audit.length ? audit.slice(0, 10).map((entry) => `<div class="compliance-row"><strong>${entry.action} ${entry.entity_type}</strong><span>${entry.reason}</span><small>${entry.actor} · ${new Date(entry.created_at).toLocaleString('ru-RU')}</small></div>`).join('') : '<div class="empty">Audit log пока пуст.</div>'; } catch (error) { $('#alert-events').innerHTML = `<div class="empty">${error.message}</div>`; } }
async function loadRiskSnapshot() { const portfolio = selectedPortfolio(); if (!portfolio) return; try { const snapshot = await api(`/api/v1/risk-snapshot?portfolio_id=${encodeURIComponent(portfolio.id)}`); const statusLabel = snapshot.status === 'healthy' ? 'Healthy' : snapshot.status === 'watch' ? 'Watch' : 'Critical'; const riskCard = $('#risk-status'); riskCard.textContent = statusLabel; riskCard.classList.remove('positive', 'warning', 'critical'); if (snapshot.status === 'healthy') riskCard.classList.add('positive'); else if (snapshot.status === 'watch') riskCard.classList.add('warning'); else riskCard.classList.add('critical'); $('#risk-var').textContent = money(snapshot.var); $('#risk-cvar').textContent = money(snapshot.cvar); $('#risk-drawdown').textContent = `${Number(snapshot.max_drawdown || 0).toFixed(1)}%`; $('#risk-concentration').textContent = `${Number(snapshot.concentration || 0).toFixed(1)}%`; const breaches = snapshot.breaches && snapshot.breaches.length ? snapshot.breaches : ['Нет активных нарушений лимитов.']; $('#risk-breaches').innerHTML = breaches.map((item) => `<div class="risk-item ${snapshot.status === 'healthy' ? 'safe' : snapshot.status === 'watch' ? 'warn' : 'danger'}">${item}</div>`).join(''); $('#risk-result').classList.remove('hidden'); $('#risk-result').textContent = snapshot.status === 'healthy' ? 'Портфель в пределах допустимого риска.' : snapshot.status === 'watch' ? 'Есть риск, но в допустимой зоне.' : 'Необходимо срочно снизить риск/экспозицию.'; } catch (error) { $('#risk-breaches').innerHTML = `<div class="risk-item danger">${error.message}</div>`; $('#risk-result').classList.remove('hidden'); $('#risk-result').textContent = error.message; } }
async function runScenario() { const portfolio = selectedPortfolio(); if (!portfolio) return; const action = $('#scenario-action').value; const payload = { action, instrument: $('#scenario-instrument').value.toUpperCase(), side: $('#scenario-side').value, quantity: Number($('#scenario-quantity').value || 0), price: Number($('#scenario-price').value || 0), risk_percent: Number($('#scenario-risk-percent').value || 0) }; const output = $('#scenario-result'); output.textContent = 'Расчет влияния...'; try { const impact = await api('/api/v1/risk-scenario', { method: 'POST', body: JSON.stringify({ ...payload, portfolio_id: portfolio.id }) }); const delta = (value, suffix = '') => `${value >= 0 ? '+' : ''}${Number(value).toFixed(1)}${suffix}`; output.innerHTML = `<strong>После сценария: ${impact.after.status}</strong><span>Exposure ${money(impact.after.exposure)} (${money(impact.delta_exposure)})</span><span>VaR ${money(impact.after.var)} (${money(impact.delta_var)})</span><span>Drawdown ${Number(impact.after.max_drawdown).toFixed(1)}% (${delta(impact.delta_drawdown, '%')})</span><span>Concentration ${Number(impact.after.concentration).toFixed(1)}% (${delta(impact.delta_concentration, '%')})</span>`; } catch (error) { output.textContent = error.message; } }
function updateScenarioControls() { const reduce = $('#scenario-action').value === 'reduce_risk'; ['scenario-instrument-field', 'scenario-side-field', 'scenario-quantity-field', 'scenario-price-field'].forEach((id) => $(`#${id}`).classList.toggle('hidden', reduce)); $('#scenario-risk-field').classList.toggle('hidden', !reduce); runScenario(); }
async function loadAnalytics() { const portfolio = selectedPortfolio(); if (!portfolio) return; const data = await api(`/api/v1/analytics?portfolio_id=${encodeURIComponent(portfolio.id)}`); $('#analytics-count').textContent = data.trade_count; $('#analytics-checklist').textContent = `${Math.round(data.checklist_rate)}%`; const render = (items, empty) => { const entries = Object.entries(items); return entries.length ? entries.map(([name, count]) => `<div class="limit-row"><strong>${name}</strong><span>${count} сдел.</span></div>`).join('') : `<div class="empty">${empty}</div>`; }; $('#analytics-strategies').innerHTML = render(data.strategies, 'Стратегии пока не указаны.'); $('#analytics-tags').innerHTML = render(data.tags, 'Теги пока не добавлены.'); }
async function loadLedger() { const portfolio = selectedPortfolio(); if (!portfolio) return; const entries = await api(`/api/v1/ledger?portfolio_id=${encodeURIComponent(portfolio.id)}`); $('#ledger-list').innerHTML = entries.length ? entries.map((entry) => `<div class="ledger-row"><strong>${entry.type.toUpperCase()}</strong><span>${entry.instrument || '—'}<small class="subtext">${entry.side || 'entry'}</small></span><span>${entry.quantity || 0}<small class="subtext">${entry.currency || 'USD'}</small></span><span>${money(entry.amount)}<small class="subtext">${new Date(entry.created_at).toLocaleString('ru-RU')}</small></span><span>${entry.reason || '—'}<small class="subtext">${entry.created_by || 'system'}</small></span></div>`).join('') : '<div class="empty">Записи ledger ещё не добавлены.</div>'; }
async function login(email, password, register = false) { const path = register ? '/api/v1/auth/register' : '/api/v1/auth/login'; const result = await api(path, { method: 'POST', body: JSON.stringify({ email, password }) }); if (register) { toast('Account created. Sign in to continue.'); setAuthMode('login'); return; } state.token = result.token; state.refreshToken = null; state.email = result.user.email; localStorage.setItem('riskledger_token', state.token); localStorage.removeItem('riskledger_refresh_token'); localStorage.setItem('riskledger_email', state.email); setView(true); await loadPortfolios(); }
function setAuthMode(mode) { document.querySelectorAll('[data-auth-mode]').forEach((tab) => tab.classList.toggle('active', tab.dataset.authMode === mode)); $('#auth-copy').innerHTML = mode === 'login' ? '<p class="eyebrow">С возвращением</p><h2>Откройте портфель</h2><p class="muted">Следите за результатом без лишнего шума.</p>' : '<p class="eyebrow">Начните работу</p><h2>Создайте аккаунт</h2><p class="muted">Ваш журнал операций начинается с первой сделки.</p>'; $('#auth-submit').textContent = mode === 'login' ? 'Войти' : 'Создать аккаунт'; $('#auth-form').dataset.mode = mode; }
async function boot() { if (!state.token && !state.refreshToken) { try { const session = await api('/api/v1/auth/refresh', { method: 'POST', skipRefresh: true }); state.token = session.token; localStorage.setItem('riskledger_token', state.token); } catch { return; } } try { setView(true); await loadPortfolios(); } catch { localStorage.clear(); state.token = null; state.refreshToken = null; setView(false); } }
document.querySelectorAll('[data-auth-mode]').forEach((tab) => tab.addEventListener('click', () => setAuthMode(tab.dataset.authMode)));
$('#auth-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await login($('#auth-email').value, $('#auth-password').value, event.currentTarget.dataset.mode === 'register'); } catch (error) { toast(error.message, true); } });
$('#logout').addEventListener('click', () => { localStorage.clear(); state.token = null; state.refreshToken = null; state.email = null; setView(false); });
document.querySelectorAll('.nav-item').forEach((button) => button.addEventListener('click', () => showPage(button.dataset.section)));
document.querySelectorAll('[data-section-link]').forEach((button) => button.addEventListener('click', () => showPage(button.dataset.sectionLink)));
$('#portfolio-select').addEventListener('change', async (event) => { state.portfolioId = event.target.value; localStorage.setItem('riskledger_portfolio', state.portfolioId); await Promise.all([loadDashboard(), loadRiskSnapshot()]); });
['scenario-action', 'scenario-instrument', 'scenario-side', 'scenario-quantity', 'scenario-price', 'scenario-risk-percent'].forEach((id) => $(`#${id}`).addEventListener('input', id === 'scenario-action' ? updateScenarioControls : runScenario));
$('#refresh-trades').addEventListener('click', loadTrades);
$('#import-broker').addEventListener('click', async () => { const portfolio = selectedPortfolio(); const file = $('#broker-file').files[0]; if (!portfolio || !file) return toast('Выберите файл брокера.', true); const form = new FormData(); form.append('portfolio_id', portfolio.id); form.append('source', $('#broker-source').value); form.append('file', file); try { const batch = await api('/api/v1/imports', { method: 'POST', body: form }); $('#import-summary').textContent = `Обработано: ${batch.total}. Matched: ${batch.matched}. Needs review: ${batch.needs_review}.`; toast('Импорт завершён'); await Promise.all([loadBrokerImports(), loadTrades(), loadLedger(), loadDashboard()]); } catch (error) { toast(error.message, true); } });
$('#import-trades').addEventListener('click', async () => { const portfolio = selectedPortfolio(); const file = $('#trade-file').files[0]; if (!portfolio || !file) return toast('Выберите CSV-файл.', true); const form = new FormData(); form.append('portfolio_id', portfolio.id); form.append('file', file); try { const result = await api('/api/v1/trades/import', { method: 'POST', headers: {}, body: form }); toast(`Импортировано: ${result.imported}`); await loadTrades(); await loadDashboard(); } catch (error) { toast(error.message, true); } });
$('#trade-form').addEventListener('submit', async (event) => { event.preventDefault(); const portfolio = selectedPortfolio(); if (!portfolio) return toast('Сначала создайте портфель.', true); try { await api('/api/v1/trades', { method: 'POST', body: JSON.stringify({ portfolio_id: portfolio.id, instrument: $('#trade-instrument').value.toUpperCase(), side: $('#trade-side').value, quantity: Number($('#trade-quantity').value), price: Number($('#trade-price').value), fee: Number($('#trade-fee').value || 0), strategy: $('#trade-strategy').value.trim(), notes: $('#trade-notes').value.trim(), tags: $('#trade-tags').value.split(',').map((tag) => tag.trim()).filter(Boolean), checklist_ok: $('#trade-checklist').checked }) }); event.target.reset(); toast('Сделка сохранена'); await loadTrades(); await loadDashboard(); } catch (error) { toast(error.message, true); } });
$('#new-portfolio').addEventListener('click', async () => { const name = prompt('Название портфеля'); if (!name) return; try { await api('/api/v1/portfolios', { method: 'POST', body: JSON.stringify({ name, base_currency: 'USD' }) }); toast('Портфель создан'); await loadPortfolios(); } catch (error) { toast(error.message, true); } });
$('#new-limit').addEventListener('click', async () => { const value = Number(prompt('Максимальная стоимость портфеля в USD')); if (!value) return; try { await api('/api/v1/risk-limits', { method: 'POST', body: JSON.stringify({ type: 'max_portfolio_value', value }) }); toast('Лимит добавлен'); await Promise.all([loadLimits(), loadRiskSnapshot()]); } catch (error) { toast(error.message, true); } });
$('#add-ledger-entry').addEventListener('click', async () => { const portfolio = selectedPortfolio(); if (!portfolio) return; const entryType = prompt('Тип записи', 'adjustment') || 'adjustment'; const instrument = prompt('Инструмент', 'USD') || 'USD'; const side = prompt('Направление (buy/sell)', 'buy') || 'buy'; const quantity = Number(prompt('Количество', '0') || 0); const price = Number(prompt('Цена', '0') || 0); const reason = prompt('Причина', 'manual adjustment') || 'manual adjustment'; const notes = prompt('Комментарий', 'Ручная корректировка') || 'Ручная корректировка'; try { await api('/api/v1/ledger', { method: 'POST', body: JSON.stringify({ type: entryType, instrument, side, quantity, price, reason, notes, created_by: 'user' }) }); toast('Запись ledger добавлена'); await Promise.all([loadLedger(), loadRiskSnapshot()]); } catch (error) { toast(error.message, true); } });
$('#evaluate-risk').addEventListener('click', async () => { try { const portfolio = selectedPortfolio(); const result = await api(`/api/v1/risk-evaluate?portfolio_id=${encodeURIComponent(portfolio.id)}`); $('#risk-result').classList.remove('hidden'); $('#risk-result').textContent = result.length ? `Открыто событий риска: ${result.length}.` : 'Нарушений лимитов нет.'; await Promise.all([loadRiskSnapshot(), loadDashboard()]); } catch (error) { toast(error.message, true); } });
boot();
