const state = { token: localStorage.getItem('riskledger_token'), email: localStorage.getItem('riskledger_email'), portfolios: [], portfolioId: localStorage.getItem('riskledger_portfolio') };
const $ = (selector) => document.querySelector(selector);
const api = async (path, options = {}) => {
  const headers = { 'Content-Type': 'application/json', ...(options.headers || {}) };
  if (state.token) headers.Authorization = `Bearer ${state.token}`;
  const response = await fetch(path, { ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `Request failed (${response.status})`);
  return data;
};
const money = (value) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(Number(value || 0));
const toast = (message, error = false) => { const node = $('#toast'); node.textContent = message; node.style.background = error ? '#ad4d23' : '#162329'; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2800); };
const selectedPortfolio = () => state.portfolios.find((item) => item.id === state.portfolioId) || state.portfolios[0];
const setView = (loggedIn) => { $('#auth-view').classList.toggle('hidden', loggedIn); $('#app-view').classList.toggle('hidden', !loggedIn); if (loggedIn) $('#user-email').textContent = state.email || ''; };
const showPage = (section) => { document.querySelectorAll('.page-section').forEach((node) => node.classList.add('hidden')); $(`#${section}-section`).classList.remove('hidden'); document.querySelectorAll('.nav-item').forEach((node) => node.classList.toggle('active', node.dataset.section === section)); $('#page-title').textContent = section === 'overview' ? 'Overview' : section === 'trades' ? 'Trades' : 'Risk controls'; if (section === 'trades') loadTrades(); if (section === 'risk') loadLimits(); };
async function loadPortfolios() { state.portfolios = await api('/api/v1/portfolios'); if (!state.portfolioId || !state.portfolios.some((item) => item.id === state.portfolioId)) state.portfolioId = state.portfolios[0]?.id; localStorage.setItem('riskledger_portfolio', state.portfolioId || ''); const select = $('#portfolio-select'); select.innerHTML = state.portfolios.map((item) => `<option value="${item.id}">${item.name} · ${item.base_currency}</option>`).join(''); select.value = state.portfolioId || ''; await loadDashboard(); }
async function loadDashboard() { const portfolio = selectedPortfolio(); if (!portfolio) { $('#positions').innerHTML = '<div class="empty">Create a portfolio to begin.</div>'; return; } const query = `?portfolio_id=${encodeURIComponent(portfolio.id)}`; const [summary, positions] = await Promise.all([api(`/api/v1/summary${query}`), api(`/api/v1/positions${query}`)]); $('#total-value').textContent = money(summary.total_value); $('#realized-pnl').textContent = money(summary.realized_pnl); $('#unrealized-pnl').textContent = money(summary.unrealized_pnl); $('#risk-count').textContent = summary.active_risk_events; $('#positions').innerHTML = positions.length ? positions.map((position) => `<div class="position-row"><strong>${position.instrument}<span class="subtext">${position.quantity} units</span></strong><span>${money(position.average_entry_price)}<span class="subtext">Avg entry</span></span><span>${money(position.market_value)}<span class="subtext">Market value</span></span><strong class="${position.unrealized_pnl >= 0 ? 'positive' : ''}">${money(position.unrealized_pnl)}</strong></div>`).join('') : '<div class="empty">No open positions yet.</div>'; }
async function loadTrades() { const portfolio = selectedPortfolio(); if (!portfolio) return; const list = $('#trades-list'); list.innerHTML = '<div class="empty">Loading trades...</div>'; try { const trades = await api(`/api/v1/trades?portfolio_id=${encodeURIComponent(portfolio.id)}`); list.innerHTML = trades.length ? trades.map((trade) => `<div class="trade-row"><span class="badge ${trade.side}">${trade.side.toUpperCase()}</span><strong>${trade.instrument}<span class="subtext">${new Date(trade.executed_at).toLocaleString()}</span></strong><span>${trade.quantity} units</span><strong>${money(trade.price)}</strong></div>`).join('') : '<div class="empty">No trades yet.</div>'; } catch (error) { list.innerHTML = `<div class="empty">${error.message}</div>`; } }
async function loadLimits() { const portfolio = selectedPortfolio(); if (!portfolio) return; const limits = await api(`/api/v1/risk-limits?portfolio_id=${encodeURIComponent(portfolio.id)}`); $('#limits-list').innerHTML = limits.length ? limits.map((limit) => `<div class="limit-row"><strong>${limit.type}</strong><span>${money(limit.value)}</span><span>${limit.enabled ? 'Active' : 'Off'}</span></div>`).join('') : '<div class="empty">No risk limits configured.</div>'; }
async function login(email, password, register = false) { const path = register ? '/api/v1/auth/register' : '/api/v1/auth/login'; const result = await api(path, { method: 'POST', body: JSON.stringify({ email, password }) }); if (register) { toast('Account created. Sign in to continue.'); setAuthMode('login'); return; } state.token = result.token; state.email = result.user.email; localStorage.setItem('riskledger_token', state.token); localStorage.setItem('riskledger_email', state.email); setView(true); await loadPortfolios(); }
function setAuthMode(mode) { document.querySelectorAll('[data-auth-mode]').forEach((tab) => tab.classList.toggle('active', tab.dataset.authMode === mode)); $('#auth-copy').innerHTML = mode === 'login' ? '<p class="eyebrow">Welcome back</p><h2>Open your workspace</h2><p class="muted">Track your portfolio with clarity.</p>' : '<p class="eyebrow">Start clean</p><h2>Create your workspace</h2><p class="muted">Your ledger starts with one honest entry.</p>'; $('#auth-submit').textContent = mode === 'login' ? 'Sign in' : 'Create account'; $('#auth-form').dataset.mode = mode; }
async function boot() { if (!state.token) return; try { setView(true); await loadPortfolios(); } catch { localStorage.clear(); state.token = null; setView(false); } }
document.querySelectorAll('[data-auth-mode]').forEach((tab) => tab.addEventListener('click', () => setAuthMode(tab.dataset.authMode)));
$('#auth-form').addEventListener('submit', async (event) => { event.preventDefault(); try { await login($('#auth-email').value, $('#auth-password').value, event.currentTarget.dataset.mode === 'register'); } catch (error) { toast(error.message, true); } });
$('#logout').addEventListener('click', () => { localStorage.clear(); state.token = null; state.email = null; setView(false); });
document.querySelectorAll('.nav-item').forEach((button) => button.addEventListener('click', () => showPage(button.dataset.section)));
document.querySelectorAll('[data-section-link]').forEach((button) => button.addEventListener('click', () => showPage(button.dataset.sectionLink)));
$('#portfolio-select').addEventListener('change', async (event) => { state.portfolioId = event.target.value; localStorage.setItem('riskledger_portfolio', state.portfolioId); await loadDashboard(); });
$('#refresh-trades').addEventListener('click', loadTrades);
$('#trade-form').addEventListener('submit', async (event) => { event.preventDefault(); const portfolio = selectedPortfolio(); if (!portfolio) return toast('Create a portfolio first.', true); try { await api('/api/v1/trades', { method: 'POST', body: JSON.stringify({ portfolio_id: portfolio.id, instrument: $('#trade-instrument').value.toUpperCase(), side: $('#trade-side').value, quantity: Number($('#trade-quantity').value), price: Number($('#trade-price').value), fee: Number($('#trade-fee').value || 0) }) }); event.target.reset(); toast('Trade recorded'); await loadTrades(); await loadDashboard(); } catch (error) { toast(error.message, true); } });
$('#new-portfolio').addEventListener('click', async () => { const name = prompt('Portfolio name'); if (!name) return; try { await api('/api/v1/portfolios', { method: 'POST', body: JSON.stringify({ name, base_currency: 'USD' }) }); toast('Portfolio created'); await loadPortfolios(); } catch (error) { toast(error.message, true); } });
$('#new-limit').addEventListener('click', async () => { const value = Number(prompt('Maximum portfolio value in USD')); if (!value) return; try { await api('/api/v1/risk-limits', { method: 'POST', body: JSON.stringify({ type: 'max_portfolio_value', value }) }); toast('Risk limit added'); await loadLimits(); } catch (error) { toast(error.message, true); } });
$('#evaluate-risk').addEventListener('click', async () => { try { const portfolio = selectedPortfolio(); const result = await api(`/api/v1/risk-evaluate?portfolio_id=${encodeURIComponent(portfolio.id)}`); $('#risk-result').classList.remove('hidden'); $('#risk-result').textContent = result.length ? `${result.length} risk event(s) opened.` : 'No limits breached.'; await loadDashboard(); } catch (error) { toast(error.message, true); } });
boot();
